// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Data;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(KomputronikDbContext))]
    [Migration("20250622205309_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApi.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Laptops"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Monitors"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Keyboards"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Mice"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Accessories"
                        });
                });

            modelBuilder.Entity("WebApi.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Good laptop",
                            Name = "Dell XPS 13",
                            Price = 4999.99m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "Good Monitor",
                            Name = "Samsung 24\"",
                            Price = 799.00m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Business laptop",
                            Name = "HP EliteBook 840",
                            Price = 4299.00m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "High-resolution monitor",
                            Name = "LG UltraFine 27\"",
                            Price = 1999.99m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Description = "Wireless keyboard",
                            Name = "Logitech MX Keys",
                            Price = 399.99m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 4,
                            Description = "Gaming mouse",
                            Name = "Razer DeathAdder",
                            Price = 249.00m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 5,
                            Description = "Expand your ports",
                            Name = "USB-C Hub",
                            Price = 159.00m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Description = "Apple keyboard",
                            Name = "Apple Magic Keyboard",
                            Price = 549.00m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 4,
                            Description = "Compact mouse",
                            Name = "Dell Wireless Mouse",
                            Price = 99.00m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 5,
                            Description = "Ergonomic accessory",
                            Name = "Laptop Stand",
                            Price = 129.00m
                        });
                });

            modelBuilder.Entity("WebApi.Models.Product", b =>
                {
                    b.HasOne("WebApi.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WebApi.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
